---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger
  namespace: linkerd
spec:
  chart:
    spec:
      chart: flagger
      sourceRef:
        kind: HelmRepository
        name: flagger      
  values: 
    crd:
      create: false
    meshProvider: linkerd
    metricsServer: http://prometheus.linkerd-viz:9090    
  interval: 10m0s
